//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JAFROC.rc
//
#define IDM_FILE_SELECTDATAFILE         10
#define IDM_FILE_EXIT                   11
#define IDM_ABOUTBOX                    0x0010
#define IDM_ROI                         22
#define IDM_PLOTTING                    31
#define IDM_SAMPLESIZEESTIMATION        33
#define IDM_SAMPLESIZECALCULATOR        34
#define IDM_OPTIONS_CREATEROC           40
#define IDM_OPTIONS_PSEUDOVALUEFILESFORSAS 41
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_JAFROC_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_RAW_FROC                    129
#define IDD_FIT_PLOT                    130
#define IDD_SAMPLE_SIZE                 131
#define IDR_MENU1                       132
#define IDR_TOOLBAR1                    143
#define IDR_TOOLBAR2                    145
#define IDR_TOOLBAR3                    147
#define IDR_TOOLBAR4                    149
#define IDR_TOOLBAR5                    151
#define IDR_TOOLBAR6                    153
#define IDR_TOOLBAR7                    154
#define IDR_TOOLBAR8                    155
#define IDR_MENU2                       156
#define IDR_TOOLBAR9                    156
#define IDR_MENU3                       157
#define IDR_TOOLBAR10                   157
#define IDR_MENU4                       158
#define IDR_TOOLBAR11                   158
#define IDR_MENU5                       159
#define IDR_TOOLBAR12                   159
#define IDR_TOOLBAR13                   160
#define IDR_TOOLBAR14                   161
#define IDR_TOOLBAR15                   162
#define IDR_TOOLBAR16                   163
#define IDR_TOOLBAR17                   164
#define IDR_TOOLBAR18                   165
#define IDM_FROC_JAFROC1                210
#define IDM_FROC_JAFROC1_WEIGHTED       211
#define IDM_FROC_JAFROC2                212
#define IDM_FROC_JAFROC2_WEIGHTED       213
#define IDM_FROC_MAX_NLF_ANALYSIS       214
#define IDM_FROC_MAX_LLF_ANALYSIS       215
#define IDM_EXP_TRNSFM_SPECIFICITY      216
#define IDM_EMPIRICALPLOTS              300
#define IDM_PARAMETRICPLOTS             301
#define IDM_HELP_HELP                   400
#define IDM_HELP_ABOUTJAFROC            401
#define IDC_FILENAME                    1001
#define IDC_FILE_OPEN                   1002
#define IDC_CONSOLE                     1003
#define IDC_ANALYSIS_JAFROC1            1004
#define IDC_ANALYSIS_JAFROC             1005
#define IDC_ANALYSIS_ROC                1006
#define IDC_OPTIONS_CREATEROC           1007
#define IDC_OPTIONS_CREATEPLOTS         1008
#define IDC_ANALYSIS_JAFROC1_WEIGHTED   1008
#define IDC_OPTIONS_PSEUDOVALUES        1009
#define IDC_ESTIMATION_YOU              1010
#define IDC_ANALYSIS_JAFROC_WEIGHTED    1010
#define IDC_ESTIMATION_I                1011
#define IDC_ANALYSIS_SONG_FOM_A0        1011
#define IDC_ESTIMATION_ROC              1012
#define IDC_ESTIMATION_PERFORM          1012
#define IDC_ANALYZE_DATA                1013
#define IDC_OPTIONS_CREATEPLOTS_ROC     1014
#define IDC_ANALYSIS_SONG_FOM_A1        1014
#define IDC_OPTIONS_CREATEPLOTS_AFROC   1015
#define IDC_ANALYSIS_SONG_FOM_A2        1015
#define IDC_OPTIONS_CREATEPLOTS_FROC    1016
#define IDC_ANALYSIS_ROC2               1016
#define IDC_ANALYSIS_ROI                1016
#define IDC_RAW_FROC                    1017
#define IDC_SAVE_CSV                    1018
#define IDC_RAW_FROC_PREV               1019
#define IDC_RAW_FROC_NEXT               1020
#define IDC_RAW_FROC_LABEL              1021
#define IDC_FIT_PLOT_PREV               1022
#define IDC_RAW_FROC_LABEL2             1022
#define IDC_FIT_PLOT_NEXT               1023
#define IDC_RAW_FROC_LABEL3             1023
#define IDC_FIT_PLOT_LABEL              1024
#define IDC_SM_FIT_SAVE_CSV             1026
#define IDC_PLOT_FROC                   1028
#define IDC_SS_MODALITY                 1028
#define IDC_PLOT_ROC                    1029
#define IDC_ES_ROC                      1029
#define IDC_SS_RECALCULATE              1030
#define IDC_PLOT_AFROC                  1031
#define IDC_SS_SUMMARY                  1031
#define IDC_SS_ALPHA                    1032
#define IDC_RAW_AFROC                   1032
#define IDC_RAW_PLOT_MODALITY           1032
#define IDC_SS_DESIRED_POWER            1033
#define IDC_RAW_PLOT_READER             1033
#define IDC_PLOT_READER                 1034
#define IDC_PLOT_MODALITY               1035
#define IDC_PARAM_SUMMARY               1036
#define IDC_ANALYSIS_MAX_NLF            1040
#define IDC_ANALYSIS_LESION_MAX_LLF     1041
#define IDM_ROC_HR_AUC                  2000
#define IDM_ROC_HR_SENSITIVITY          2001
#define IDM_ROC_HR_SPECIFICITY          2002
#define IDM_ROC_SONG_A1_AUC             2010
#define IDM_ROC_SONG_A1_SENSITIVITY     2011
#define IDM_ROC_SONG_A1_SPECIFICITY     2012
#define IDM_ROC_SONG_A2_AUC             2020
#define IDM_ROC_SONG_A2_SENSITIVITY     2021
#define IDM_ROC_SONG_A2_SPECIFICITY     2022
#define IDT_RUN                         32818
#define IDT_OPEN                        32820
#define IDT_METHODS                     32834
#define ID_ANALYZETHEDATA_RUN           32856
#define IDM_ANALYZETHEDATA_RUN          32857
#define IDT_EXPLORING                   32859
#define IDT_OPTIONS                     32860
#define IDT_HELP                        32861
#define IDM_FROC_CUSTOM_ANALYSIS        217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
